# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec8ac1613d63819310d646f98e5c35818d76018c15208e34b0b0c1b789c803d2b23d5ffa21f07ae915e5728ab4bc1fd513f7764d877d7b21d930d566e7a9acb3

test:
  secret_key_base: fb035e0b3c250ebc7d5e2f26a789d955d705a40c1d023c4ce7ee73c3d73ebc1984f321d116b786cc4cf4ff9348d204fe6bef3bcba6ffc3e08d3fa71026253a3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
